### ISSUE TITLE
No crate exists with this name?

### ISSUE THREAD

**Issue by viraladmin** [LukasDeco/lzw-compress#1]
error: no matching package named `lzw-compression` found
location searched: registry `crates-io`
required by package `blockchain v0.1.0

**Comment by LukasDeco** [comment]
@viraladmin here's the link: https://crates.io/crates/lzw-compress
 
 You are saying another crate is giving an error about this crate?
 
 Apologies for the major delay in getting back to you.

**Comment by LukasDeco** [comment]
@viraladmin I will resolve this since I haven't heard back. Feel free to re-open.
